# 1. What is a Python library? Why do we use Python libraries?

Answer: python library is a set of modules used to provide modularity and enhance reusability of code.

# 2. What is the difference between Numpy array and List?

Answer:

1. In numpy array it follows uniformity for efficient numerical operations whereas the python list can hold different data types makes it more flexible but not effiecient compared to numpy array

2. Numpy uses contiguous blocks of memory for optimized and fast operations to be performed whereas list are holding elements in non contiguous manner which makes it slower in iterations etc.

3. numpy array being homogeneous provides memeory efficient as compared to python list which is heterogenous

4. numpy array supports multi dimentional arrays allowing operations on higher dimentional data but the list requires nesting of other lists to perform the same which is very time and memeory consuming

# 3. Find the shape, size and dimension of the following array?
```
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
```

In [1]:
import numpy as np

In [3]:
np_arr = np.array(
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

print(np_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
print(np_arr.shape)

print(np_arr.ndim)

print(np_arr.size)

(3, 4)
2
12


# 4. Write python code to access the first row of the following array?
```
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
```

In [5]:
np_arr[0]

array([1, 2, 3, 4])

# 5. How do you access the element at the third row and fourth column from the given numpy array?

In [6]:
np_arr[2][3]

12

# 6. Write code to extract all odd-indexed elements from the given numpy array?

In [8]:
np_arr[:, 1::2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

# 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [9]:
random_matrix_3x3 = np.random.rand(3,3)

random_matrix_3x3

array([[0.96125056, 0.41317954, 0.18152231],
       [0.06498055, 0.11433866, 0.9843332 ],
       [0.79593825, 0.34149387, 0.46094858]])

8. Describe the difference between np.random.rand and np.random.randn?

Answer:

1. np.random.rand gives unifrom distributed random numbers, np.random.randn provides normal gaussian distributed random numbers

2. np.random.rand() ranges [0,1] whereas np.random.randn ranges between -infinity and +infinity

# 9. Write code to increase the dimension of the following array?

In [11]:
expanded_arr = np.expand_dims(np_arr, axis=0)

print(expanded_arr)

print(expanded_arr.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
(1, 3, 4)


# 10. How to transpose the following array in NumPy?

In [14]:
transpose = np_arr.T

print(transpose)
print(transpose.shape)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
(4, 3)


11. Consider the following matrix:
```
Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
```
Perform the following operation using Python1
,+ Index wise multiplicatio'
]+ Matrix multiplicatio'
+ Add both the matricK
-+ Subtract matrix B from
+ Divide Matrix B by A

In [15]:
matrixA = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

matrixB = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])


In [16]:
# index wise multiplication

matrixA * matrixB

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [18]:
# matrix multiplication

np.dot(matrixA, matrixB.T)

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [19]:
# add both the matrices

matrixA + matrixB

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [20]:
# subtract matrix B from matrix A

matrixB - matrixA

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [22]:
# divide matrix b by A

matrixB / matrixA

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# 12. Which function in Numpy can be used to swap the byte order of an array?

Answer: numpy.ndarray.byteswap(inplace=False)


# 13. What is the significance of the np.linalg.inv function?

Answer: this is a numpy function in linear algebra module which provides inverse of a square matrix

# 14. What does the np.reshape function do, and how is it used?

Answer: to change the shape of a matrix we use np.reshape

example: if a matrix of 3x4 matrix is created but for any operation it needs to be reshaped to 4x3, we uses np.reshape

# 15. What is broadcasting in Numpy?

Answer:

broadcasting is the feature of numpy which allows array of different shapes to be auto align and operate on element wise without replication of data which makes array operations more efficient

example: arr + 5, means broadcasting of adding 5 as an operation on arr without looping or creating any copy of the arr to do so. thats numpy broadcasting.
